# Generated by Django 3.0.1 on 2020-11-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.CharField(max_length=6)),
                ('Full_name', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(max_length=6)),
                ('Product_name', models.CharField(max_length=20)),
                ('Cost_price', models.IntegerField()),
                ('Sell_price', models.IntegerField()),
                ('Rating', models.CharField(max_length=10)),
            ],
        ),
    ]
