# Generated by Django 3.0.1 on 2020-11-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.CharField(max_length=6)),
                ('Order_id', models.CharField(max_length=6)),
                ('Product_id', models.CharField(max_length=6)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
