# Generated by Django 3.0.1 on 2020-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=6)),
                ('Customer_id', models.CharField(max_length=6)),
                ('Date', models.DateField()),
                ('Order_status', models.CharField(max_length=8)),
            ],
        ),
    ]
