# Generated by Django 3.0.1 on 2020-11-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.CharField(max_length=6)),
                ('Order_id', models.CharField(max_length=6)),
                ('Product_id', models.CharField(max_length=6)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Date', models.DateField()),
                ('Order_status', models.CharField(max_length=8)),
            ],
        ),
    ]
