# Generated by Django 3.0.1 on 2020-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0004_cart_contains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_contains',
            name='Date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cart_contains',
            name='Order_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_status',
            field=models.CharField(max_length=10),
        ),
    ]
