# Generated by Django 3.0.1 on 2020-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0005_auto_20201106_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_contains',
            name='Order_status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='orders',
            table='retailers_orders',
        ),
    ]
